### ISSUE TITLE
Mac and iOS and some other browers need info method to check iframe access

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/deso-workspace#17]
On Mac and iOS the iframe access is limited after a browser session access need to be granted again by tapping on the iframe. Like diamond and bitclout do. 

In that case the iframe identity info method detects it does not have access to the iframe local storage. Happens on Mac and iOS. In that case you need to show to iframe so a user can tap it to gain access. Without it transactions fail. Normally some logic needs to be added like:

Call info method (after initialize)
Check if browser supported and if has sufficient access
Show iframe at full width and height
Catch storageGranted post message to hide iframe.
to check the access something like

if(event.data.payload && event.data.payload.browserSupported){ if(!event.data.payload.hasStorageAccess || !event.data.payload.hasLocalStorageAccess){ //set iframe display to block
Can be used.

#16 fixes the style of iframe top so it can be shown for tapping. But the above logic needs to be added. Can be done after initialize and only if a logged in user is detected.

**Comment by DeSoDog** [comment]
Just got my mac, will be focusing on this soon. Thanks for waiting!

**Comment by mvanhalen** [comment]
@DeSoDog great, let me know if you need some input or testing.

**Comment by jackson-dean** [comment]
I have this PR for it. lmk if this will work @mvanhalen https://github.com/deso-protocol/deso-workspace/pull/41

**Comment by mvanhalen** [comment]
Awesome @jackson-dean @DeSoDog will check it out and remove some of my own code for this.

**Comment by jackson-dean** [comment]
> Awesome @jackson-dean @DeSoDog will check it out and remove some of my own code for this.

Just lmk if we can resolve this one @mvanhalen

**Comment by mvanhalen** [comment]
@jackson-dean only issue I seen is #43 which prevents me from publishing to test on iphone. If that pr is merged and published I can complete testing.

**Comment by mvanhalen** [comment]
Was gone for a few days. Working for us on [nftz.me](nftz.me) now. iPhone and Mac working correctly now.

**Comment by mvanhalen** [comment]
Seems I´m getting the iframe prompt stuck in some cases open in standalone mode / webapp and android . I think it should always close when clicked / tapped and maybe auto hide after x secs. Will check that in more detail. Reverting some code in the mean time. @jackson-dean

**Comment by mvanhalen** [comment]
Any update on the the iframe blocking in web views of other apps (telegram, discord, gmail)? And checking if the checks only apply to the correct browsers / OS? @jackson-dean @DeSoDog. In all ceases even if the right is not giving somehow the iframe should close I think.

**Comment by jackson-dean** [comment]
@mvanhalen I will look into this and get back to you.

**Comment by jackson-dean** [comment]
@mvanhalen After investigating this, the issue with the iframe inside a native mobile app webview seems to be that the posMessage call we listen for actually gets sent to the host web app and not the parent page. Such that when the user taps on the iframe we never get a response letting us know if the storage access was granted and so it just hangs waiting since this postMessage is what tells the identity library that it should close.

There is also not a great way to detect if a page is loading in a mobile webview or a mobile browser. For mobile browsers things should work as expected, so that leaves this problem of how to deal with the mobile web view. Before I implement anything as a workaround, I wanted to get your thoughts about what would make the most sense for your use case. A few options I have considered:
- Have a timeout that automatically closes the iframe after some duration if we have not gotten the storage granted postMessage payload.
- Add a manual dismiss button that we control from our side which allows a user to at least dismiss the "tap to unlock" screen. 

Unfortunately, in the case a mobile app webview, I'm not sure there is a great way to know that storage was granted properly since we never receive the postMessage call from the iframe.

let me know what you think about all this and let's try and figure out a reasonable UX for this.

**Comment by mvanhalen** [comment]
@jackson-dean that is exactly the issue. I would opt for a timeout after a user clicks on the iframe. If the storage granted post message does not arrive auto close it after 1 or 2 secs.

**Comment by jackson-dean** [comment]
@mvanhalen the problem we face is that we cannot listen to clicks within the iframe. This is completely handled by the embedded identity angular app, so it is a bit tricky since we cannot listen directly for the user's interaction. This is why I suggest potentially adding our own "dismiss" button somewhere on the page that we own and have it look integrated with the iframe though it is really on our page. wdyt?

**Comment by jackson-dean** [comment]
@mvanhalen this SO thread has some interesting hacks to deal with a similar scenario. Let me do a little more experimenting.

**Comment by mvanhalen** [comment]
> @mvanhalen this SO thread has some interesting hacks to deal with a similar scenario. Let me do a little more experimenting. https://stackoverflow.com/questions/2381336/detect-click-into-iframe-using-javascript

Yeah would assume it´s possible since you create the iframe in the package and can assign an id or other attribute. If not maybe a tweak to the identity frame code is needed. Good luck tinkering!

**Comment by jackson-dean** [comment]
@mvanhalen It is not possible to listen for clicks in the iframe but there are hacks of listening for "blur" on the parent window. But it is unfortunately impossible to listen to clicks within the iframe context. One additional strange quirk I have discovered is that you can actually get it to work by following these steps:
- On your mobile device open an app that has an embedded webview (I am testing with metamask for instance, but any should work)
- Initiate the "tap to unlock" flow (you will be stuck here, continue to next step).
- Now within same webview, change the url to a different page that uses identity (https://hub.deso.org should work).
- After the other page has loaded change the url back to your original web app's url.
- Initiate tap to unlock. This time when you tap you should get prompted by a native apple prompt asking if you want to allow storage. If you allow it, the tap to unlock screen will go away and things should work.

Obviously this is not the ideal flow! But it is interesting that this seems to force it into working. Please let me know if you can reproduce the above. I am still investigating why this leave and come back flow jobs it into working.

**Comment by jackson-dean** [comment]
@mvanhalen I have more findings that explain my previous comments:

super confusing but I finally figured out how to reliably get it to work after reading through this bug report https://bugs.webkit.org/show_bug.cgi?id=193277

The issue seems if you visit a site directly and request access via the identity iframe it is not acting as a "first party"
In order to get this "first party" status, the user must navigate to the domain directly (just go directly to [identity.deso.org](http://identity.deso.org/) etc). maybe this is why hub.deso.org works as well, though not sure.

Now when the user comes back to your page that embeds identity everything works fine.

So, anyway I get past the "tap to unlock" page reliably with this strategy. though we can make this smoother, like provide a link or something on our top level page. Not sure the UX around this, but will discuss internally how we can leverage this to get it to work. BUT now when I try to open the identity window to login (after granting access) it just redirects me to [deso.org](http://deso.org/) so that part is also messed up even if we can get past the "tap to unlock." Will report back when I have more info.

**Comment by jackson-dean** [comment]
And the plot thickens unfortunately. We can use the "blur" trick to detect if the user clicked, but in some cases the browser presents a native dialog asking the user explicitly to confirm or deny granting access, so just tapping is not enough in all cases. A user must tap _and then_ click "allow" on a native browser dialog before we can proceed. So, there are some thorny issues here. Will need to consider it more.

**Comment by jackson-dean** [comment]
@mvanhalen some good news. I created this PR against the identity app to address the stuck "tap to unlock" issue https://github.com/deso-protocol/identity/pull/172 Will not be able to use until it's deployed, but it is merged!

**Comment by mvanhalen** [comment]
Thanks for your time investigating this thoroughly and coming up with a solution.

**Comment by jackson-dean** [comment]
Forgot to follow up here, but this should be merged now. Also there is a new boolean property on the `storageGranted` payload called `status`. If `true` it means the user granted access. If `false` it means the opposite. In either case, it should remove iframe.

**Comment by mvanhalen** [comment]
It´s being using on https://nftz.me now. Removed our own window handlers. Will close this issue. Thanks for the update
